"""
Write lib/server/fontCoverage.ts: the code points the report's font can draw.

The PDF report embeds Noto Sans (Latin, Greek, Cyrillic). A character outside
it would print as an empty box, so the report folds it to ASCII or drops it —
the same rule the Python report applied to its narrower cp1252 fonts. This
table is how the TypeScript knows which is which, without loading the font at
runtime. Re-run after changing the fonts:

    python scripts/gen_font_coverage.py
"""

from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = sorted((ROOT / "lib" / "server" / "fonts").glob("*.ttf"))

covered = None
for path in FONTS:
    cmap = set(TTFont(path).getBestCmap())
    covered = cmap if covered is None else covered & cmap  # every style must have it

ranges = []
for cp in sorted(covered):
    if ranges and cp == ranges[-1][1] + 1:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp])

body = ",\n".join(f"  [0x{a:04x}, 0x{b:04x}]" for a, b in ranges)
out = ROOT / "lib" / "server" / "fontCoverage.ts"
out.write_text(
    "// Generated by scripts/gen_font_coverage.py from the fonts in\n"
    "// lib/server/fonts/ — do not edit by hand.\n"
    f"// {len(covered)} code points in {len(ranges)} ranges, present in every style.\n\n"
    "export const FONT_RANGES: readonly (readonly [number, number])[] = [\n"
    f"{body},\n];\n",
    encoding="utf-8",
)
print(f"{len(covered)} code points, {len(ranges)} ranges -> {out.relative_to(ROOT)}")
