"""
Generate lib/pyUnicode.ts — the character tables Python's str methods use.

JavaScript's \\s, \\p{Nd} and friends are *close* to Python's str.isspace(),
str.isdigit() and float()'s digit handling, but not identical (JS counts
U+FEFF as whitespace, Python counts U+001C–U+001F and U+0085; Python's isdigit
includes superscripts). The port needs Python's behaviour exactly, so the
tables are taken from Python itself rather than approximated.

Run with the same Python the original app uses:

    python parity/gen_unicode_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "lib" / "pyUnicode.ts"


def ranges(codepoints: list[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = prev = codepoints[0]
    for cp in codepoints[1:]:
        if cp == prev + 1:
            prev = cp
            continue
        out.append((start, prev))
        start = prev = cp
    out.append((start, prev))
    return out


def fmt(rs: list[tuple[int, int]]) -> str:
    return ",\n  ".join(f"[0x{a:04x}, 0x{b:04x}]" for a, b in rs)


ALL = range(0x110000)
space = [c for c in ALL if chr(c).isspace()]
digit = [c for c in ALL if chr(c).isdigit()]
# Characters float() accepts as digits, with their value.
decimal_zero_runs: list[tuple[int, int]] = []
for a, b in ranges([c for c in ALL if unicodedata.decimal(chr(c), None) is not None]):
    # Each run is one or more blocks of 0..9; record where each block's 0 is.
    for zero in range(a, b + 1, 10):
        assert unicodedata.decimal(chr(zero)) == 0, hex(zero)
        decimal_zero_runs.append((zero, zero + 9))

OUT.write_text(
    f"""// GENERATED by parity/gen_unicode_tables.py from Python {sys.version.split()[0]}
// (Unicode {unicodedata.unidata_version}). Do not edit by hand.

/** Code-point ranges for which Python's str.isspace() is True. */
export const PY_SPACE: ReadonlyArray<readonly [number, number]> = [
  {fmt(ranges(space))},
];

/** Code-point ranges for which Python's str.isdigit() is True. */
export const PY_DIGIT: ReadonlyArray<readonly [number, number]> = [
  {fmt(ranges(digit))},
];

/** Blocks of ten decimal digits float() accepts, as [zero, nine]. */
export const PY_DECIMAL_BLOCKS: ReadonlyArray<readonly [number, number]> = [
  {fmt(decimal_zero_runs)},
];
""",
    encoding="utf-8",
)
print(f"wrote {OUT} — {len(ranges(space))} space ranges, "
      f"{len(ranges(digit))} digit ranges, {len(decimal_zero_runs)} decimal blocks")
